version: '3.8'

services:
  postgres:
    image: postgres:15.14
    container_name: product-trial-postgres
    environment:
      POSTGRES_DB: productdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - product-trial-network
    restart: unless-stopped


volumes:
  postgres_data:

networks:
  product-trial-network: