version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: product-trial-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: product_trial
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/infrastructure/src/main/resources/db/migration:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: