server:
  port: 8080
spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://localhost:5432/product_trial
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration
