server:
  port: 8080
spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://localhost:5432/product_trial
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration

# Springdoc OpenAPI/Swagger configuration
springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    doc-expansion: none
    enabled: true
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
